apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type:
    NodePort
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400