apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type:
    NodePort
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30500