apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  type: 
    NodePort
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30401
  